version: '3.10'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: mainapp-web
    ports:
      - 8000:8000
    env_file:
      - .docker.env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:15.1-alpine
    container_name: mainapp-db
    restart: always
    ports:
      - 9000:5432
    env_file:
      - .docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - menus_db:/var/lib/postgresql/data

volumes:
    menus_db:
      name: menus_db