version: '3.10'

services:
  test_app:
    build:
      context: .
      dockerfile: .test.Dockerfile
    container_name: testapp-web
    ports:
      - 8001:8000
    env_file:
      - .docker.env
    depends_on:
      test_db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && python -m pytest -v"


  test_db:
    image: postgres:15.1-alpine
    container_name: testapp-db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - test_db:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:latest
    env_file:
      - .docker.env
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5


volumes:
  test_db:
    name: test_db
